// ─── NAVIGATION ────────────────────────────────────────────────────────────
export const PAGES = [
  { id: 'home',       label: 'Home' },
  { id: 'origins',    label: 'Origins' },
  { id: 'chud',       label: 'The Chud' },
  { id: 'disciples',  label: 'The Disciples' },
  { id: 'chronicles', label: 'Chronicles' },
  { id: 'texts',      label: 'Sacred Texts' },
  { id: 'laws',       label: 'The Laws' },
  { id: 'prayer',     label: 'Prayer' },
  { id: 'game',       label: 'Waring Frames' },
]

// ─── PILLARS ────────────────────────────────────────────────────────────────
export const PILLARS = [
  { n:'I',   sk:'Pomalý pohyb',      en:'Slow Movement',   body:'The Chud does not rush. <em>Speed without direction is just fast lostness.</em> Walk slowly enough to see what is in front of you. Kopecky demonstrated this by always being the last to arrive at everything and always being right about what he found when he got there — and, on four occasions, by arriving so slowly that he was reportedly seen departing a place before he had finished arriving at it, a contradiction the Council has filed under "movement."' },
  { n:'II',  sk:'Tiché vedenie',     en:'Quiet Knowing',   body:'The Chud knows things without announcing the knowing. The knowledge is demonstrated in action. Kopecky rarely explained his reasoning and was correct with such consistency that people stopped asking and simply waited for results. On the matter of the harvest of Year Eight, he was correct before the seeds were planted, which he did not consider prophecy but "paying attention slightly upstream of events."' },
  { n:'III', sk:'Lesná trpezlivosť', en:'Forest Patience', body:'Named for three days in the spruce forest that several almanacs record as a single afternoon. The Chud can wait. Not passively — <em>actively.</em> The Chud waits the way a spruce waits: rooted, upright, gathering light. Kopecky institutionalised this by never answering any question he considered premature, which included most questions asked before noon, and one question — about the satchel — that he has now declined to answer for upward of four centuries, patiently, as though the asker is still standing there.' },
  { n:'IV',  sk:'Poctivý chlieb',    en:'Honest Bread',    body:'Whatever you make, make it properly. Whatever you offer, offer it whole. Bread must be made correctly, salted correctly, shared correctly. Kopecky could identify a poorly made loaf at twelve paces — and, the bakers of three valleys swear, a poorly made loaf could identify <em>him</em>, going quietly stale in his presence out of shame. <em>He also never let a good loaf pass without comment.</em> His tone was different. The good loaves are said to have lasted longer than bread should.' },
  { n:'V',   sk:'Tatranská pamäť',   en:'Tatra Memory',    body:'The Chud does not forget. Not as a grudge — though Kopecky demonstrated the two are not mutually exclusive — but as a form of respect. To remember is to honour what happened. The mountains remember every storm; Kopecky remembers every slight, every kindness, every wrong room assignment at every inn, and, the record notes uneasily, several events that have not yet occurred, which he remembers in advance, "to save time."' },
  { n:'VI',  sk:'Správne odísť',     en:'Right Leaving',   body:'The Chud knows when to go. Kopecky always left at the correct moment — usually before the bill, almost always before the situation deteriorated, and <em>once, memorably, slightly too early,</em> departing a gathering before an event that, because he had left, then did not occur, sparing everyone, which he counts as the leaving working perfectly and others count as confusing. He called this pillar the most important. He also had the most trouble with it personally, and walked into a fog over it.' },
]

// ─── DISCIPLES ──────────────────────────────────────────────────────────────
export const DISCIPLES = [
  {
    id: 'ayub',
    name: 'Ayub Jamma',
    epithet: 'The Echo That Arrived First',
    origin: 'Claims the Eastern Váh · The Váh Has Filed a Denial',
    role: 'Merchant of Borrowed Thoughts · Self-Anointed First Disciple · Owner of a Mirror That Has Started Talking Back',
    status: 'Active · Apostleship Self-Granted and Self-Witnessed · Currently Suing the Concept of Originality',
    bio: `Ayub Jamma arrived in Prvá Dolina in Year Four already explaining something. Nobody had asked. He has not stopped since, and the Council's best reconstruction is that he began the sentence somewhere east of the Váh and simply walked west until he reached an audience. He introduced himself as "the man you have been waiting for." Kopecky, who had been waiting for stew, said the stew was the thing he had been waiting for, and that Ayub had arrived during the wait but was not the object of it. Ayub recorded this as an endorsement.

The thing about Ayub — the thing the scribes circle and underline and then nervously erase — is that he plagiarises in advance. He does not merely restate Kopecky's teachings with his own name attached; he has, on four documented occasions, stated them <em>before Kopecky said them</em>, then accused Kopecky of borrowing. The Council convened on this. The Council adjourned without conclusion. Ayub published the minutes of the adjournment under the title <em>Jamma on Patience,</em> crediting himself.

He carries a copper mirror, hand-polished, which he consults before speaking. In Year Six the mirror began, according to three witnesses and Ayub's own furious denials, to answer him a half-second before he spoke — agreeing with him, but early, which Ayub found intolerable, because being agreed with in advance felt uncomfortably like being plagiarised, and he knew, better than anyone alive, exactly how that felt. He has since covered the mirror. He still consults it. He consults the cover.`,
    incidents: [
      {
        title: 'The Pamphlet That Wrote Itself, Allegedly, According to Ayub',
        body: `<em>The Jamma Principles</em> exists in nine editions, each longer than the last, each claiming the previous was forged. The sixth edition contains a chapter accusing the fifth edition of plagiarism. The seventh edition settled the matter by plagiarising both. Kopecky owns all nine. He has read all nine. He has said nothing across all nine, and the silence has now lasted long enough that Ayub has begun citing it as a foreword — "with the tacit blessing of the Tatras" — in the tenth edition, which is not yet written, which Ayub is already defending against critics who do not yet exist and may, the Council fears, be summoned into existence by the strength of his defence.`
      },
      {
        title: 'The Debate That Ayub Won Before It Began',
        body: `Ayub challenged Kopecky to a contest of wisdom in the Nitra market. He delivered a ninety-minute opening statement, the last forty minutes of which were an apology to the crowd for how decisively the contest was about to end in his favour. Kopecky arrived at minute ninety-one. He asked one question: "Name a single thing you have ever been wrong about." Ayub answered instantly, fluently, at great length, and the horror of the market square — recorded by four scribes who later compared notes and wept — was that every example he gave of being wrong was, on inspection, an example of him being right, and the crowd realised, slowly, that Ayub had never been wrong about anything, not because he was always right, but because he had quietly redefined "wrong" to mean "a kind of advanced rightness others lack the framework to perceive." Kopecky left to get stew. Ayub declared victory. Two members of the crowd agreed with him, and were later found to be Ayub, twice.`
      },
      {
        title: 'The Mirror Incident',
        body: `When Kopecky finally looked into Ayub's copper mirror — once, in Year Eight, at Ayub's insistence — the mirror is recorded to have shown not Kopecky but the back of Kopecky's head, as though he were looking at himself walking away. Kopecky studied this for some time and said: "Yes. That is correct." He returned the mirror. Ayub looked into it immediately afterward and saw himself, as always, facing forward, beaming, and took this as proof of his superior relationship with reflection. He has never understood why Kopecky kept the back of his own head and Ayub kept only his face. The Council understands. The Council will not be explaining.`
      },
    ],
    kopecky_quote: `"Ayub says things I have said. Ayub says things I have not yet said. The second is more impressive and I will not be telling him so, because he would say he taught it to me, and the unbearable part — the part I turn over at night the way the river turns a stone — is that I am no longer entirely certain he did not."`,
    kopecky_source: 'To the apostle Vladimír · Year Eight · The only recorded instance of Kopecky admitting uncertainty about his own authorship',
    disciple_quote: `"Kopecky is a good man. A derivative man, but a good one. People ask how I bear it — watching him receive credit for the framework. I tell them: greatness is patient. Jamma is patient. The Chud, after all, was simply Jamma waiting to be named, and I have graciously allowed another to name it. That is the true first principle. It is also the ninth. I contain the others between."`,
    disciple_source: 'Ayub Jamma · Foreword to an edition that does not exist yet · Already in circulation somehow',
  },
  {
    id: 'abdullah',
    name: 'Abdullah Ershdat',
    epithet: 'He Who Negotiates With Bears',
    origin: 'The Hron Valley · Returned There Once · The Bears Sent Him Back',
    role: 'Diplomat to the Animal Kingdom (Unrecognised by the Animal Kingdom) · Believer in the Reasonableness of All Things · The Funniest Thing That Happened During the Walking',
    status: 'Active · Remarkably · Against the Direct Wishes of Several Bears',
    bio: `Abdullah Ershdat believes that everything can be reasoned with. Not as a philosophy — as a load-bearing certainty he has never once tested against evidence, because every time the evidence arrives in the form of a charging animal, Abdullah interprets his own survival as the negotiation succeeding. He has reasoned with bears, with the weather, with a rockslide (mid-slide), with a fever, and, in Year Nine, with the concept of Tuesday, which he felt had been treating him unfairly. He reports that all of these negotiations went well. He is, by every external measure, the luckiest man who has ever lived, and he attributes none of it to luck, which Kopecky finds the single most fascinating thing he has encountered in fourteen years of walking.

The bears are the central matter. Abdullah does not fight bears, flee bears, or avoid bears. He addresses them. He has a tone he uses — witnesses describe it as "the tone of a man reminding an old friend of a shared appointment" — and he opens, always, with the same line: "Now, we both know how this ends." The unbearable thing, the thing Kopecky laughed at exactly once and never again, is that the bears, increasingly, seem to know how it ends too, and it does not end the way bears usually end things. Three bears have been observed leaving conversations with Abdullah looking, the scribes wrote, "reconsidered."

Kopecky mocks Abdullah more than any other disciple, openly, frequently, and with what the Council has classified as "affection so deeply buried it requires excavation equipment." It is understood that Kopecky's mockery is the closest thing he has to tenderness, and that Abdullah, who reasons with everything, has correctly reasoned this out, and says nothing, and simply continues being mocked, which he has decided is a kind of love. He is right. This is the only thing Abdullah has ever been right about and he does not know that it is the only thing.`,
    incidents: [
      {
        title: 'The Bear Who Filed a Complaint',
        body: `In Year Seven a bear of the upper Hron — large, established, locally feared — encountered Abdullah on a narrow path and did the thing bears do. Abdullah said, "Now, we both know how this ends," and began to outline a compromise. What was recorded next, by two terrified woodcutters in a tree, is that the bear sat down. Not in submission — in the posture, the woodcutters insisted, of a creature preparing to make its own case. The two of them conversed for an hour. The bear left first. Abdullah reported the bear had "raised some fair points about the path and we've agreed to share it." The path has, in fact, been shared ever since. The bear has been seen using the agreed schedule. Kopecky, told of this, was silent for a long time and then said the sentence the Church has never been able to interpret: "Abdullah is the only one of them who is actually doing it. He simply does not know what 'it' is." He would not elaborate.`
      },
      {
        title: 'The Negotiation With Tuesday',
        body: `Abdullah became convinced, in Year Nine, that Tuesdays specifically were conspiring against him — that his misfortunes clustered there. Rather than accept this or dismiss it, he did the Abdullah thing: he addressed Tuesday directly, aloud, on a Monday evening, laying out his grievances and proposing terms. The following Tuesday was, by every account in the valley, the single most pleasant day of that year — mild, lucky, unhurried, with bread that came out correctly in every household. Abdullah considered the matter settled. The Council of Devín has formally declined to investigate whether Abdullah successfully negotiated with a day of the week, on the grounds that the only two possible findings — that he did, or that he did not and it happened anyway — are both unacceptable.`
      },
      {
        title: 'What Kopecky Laughed At',
        body: `The one documented laugh of Kopecky in all of scripture occurred while reading Abdullah's own written account of his bear diplomacy, specifically a passage in which Abdullah, with total sincerity, advised future readers on body language: "Do not show the bear fear, but also do not show the bear that you are not showing it fear, as bears find this insulting." Kopecky read this line, set down the page, and laughed — once, fully, a sound the apostle Vladimír described as "like a door opening in a house everyone thought was empty." Then he stopped, picked the page back up, and said, quietly, "He is not wrong, though." This is the part of the story the Church finds most difficult: that the laugh and the agreement came from the same man in the same minute.`
      },
    ],
    kopecky_quote: `"Everyone asks why I am hardest on Abdullah. It is because Abdullah is the only one who might actually be a god and has decided instead to be kind to bears. Do you understand what that costs? He could rule the weather. He negotiates with it as an equal. I correct men because they are wrong. I mock Abdullah because he is right in a way that frightens me, and mockery is the only sound I can make that is not awe."`,
    kopecky_source: 'To the apostle Vladimír · Year Ten · Recorded, then sealed for a century, then unsealed because Vladimír said Abdullah deserved to never know',
    disciple_quote: `"Kopecky is gruff with me. That is all right. We both know how this ends. I said the same thing to the bear, and the bear and I are friends now. I am a patient man. I have time. I have negotiated with time. It was very reasonable about it."`,
    disciple_source: 'Abdullah Ershdat · The Hron path · Speaking to no one in particular, possibly to the path',
  },
  {
    id: 'enrico',
    name: 'Enrico',
    epithet: 'The Yes That Echoes in All Directions',
    origin: 'The South · Agreed That It Was the South When Asked · Then Agreed It Was the North',
    role: 'Agreer · Concordance Made Flesh · Holds No Position and All Positions · Structural Hazard at Debates',
    status: 'Active · In Agreement With This Status · And With Its Opposite',
    bio: `Enrico agrees. This is not a personality trait; the Council has upgraded it to a physical property. Enrico agrees with whatever is said to him, including contradictions, including statements made simultaneously by two people, including, on one catastrophic occasion in Year Six, both sides of a war negotiation, which he attended as a neutral party and accidentally ended by agreeing so completely with everyone that both armies believed they had won and went home. The peace has held. Nobody is comfortable with how it was achieved.

He agrees with everyone except Kopecky. This is the one exception, and it is total, and it is the great mystery of his life. When Kopecky says a thing is so, Enrico — who has never disagreed with another living soul — feels something rise in him that he can only describe as "a no with no bottom." He does not understand it. Kopecky does. Kopecky has said, once, that Enrico's disagreement is the only honest thing in the valley, "because it costs him everything and he does it anyway," and that a man who agrees with all of creation but balks at one voice has located, by pure instinct, the one voice worth balking at. Enrico, told this, disagreed with it, which Kopecky said proved the point, which Enrico also disagreed with, weeping.

The disagreement has begun to spread inward. Witnesses in Year Nine report Enrico agreeing with himself and then, a beat later, disagreeing — a man becoming a debate. The Council watches this with concern. Kopecky watches it with something closer to pride. "He is learning to be two people," Kopecky said. "Most men never manage to be one."`,
    incidents: [
      {
        title: 'The War He Ended By Accident',
        body: `Summoned to the border dispute between the Nitra and Hron valleys as a neutral witness — chosen specifically because he had no opinions — Enrico listened to the Nitra delegation and agreed that their claim was just. He then listened to the Hron delegation and agreed that <em>their</em> claim was just, with equal warmth, in the same meeting, while the Nitra delegation was still in the room. Rather than collapse into renewed conflict, both sides experienced the profound and unfamiliar sensation of being completely understood, and, disarmed by it, proposed terms. The terms were generous. Enrico agreed with them. Everyone went home feeling heard. Historians call it the Concordance of Devín. Enrico calls it "a nice day." The two characterisations are not in tension, which is itself very Enrico.`
      },
      {
        title: 'The One Disagreement',
        body: `In Year Five, in front of the full assembly, Kopecky stated that the spruce grows toward the light. This is true. It is among the truest things a person can say. Enrico opened his mouth to agree — and could not. The assembly watched a man who had never disagreed with anything struggle, visibly, against a force he had no name for, until he finally said, in a small and horrified voice, "I do not think that is so." The spruce, that very afternoon, was observed by three farmers to grow very slightly downward, for one day, before resuming its proper direction — the Church has never determined whether the tree was correcting Enrico or comforting him. Kopecky said only: "There it is." He has never explained what "it" was.`
      },
      {
        title: 'The Argument With Himself',
        body: `By Year Nine, Enrico's interior had begun to fracture along the fault line Kopecky opened. He was observed at the well, alone, conducting a full debate — proposing, countering, conceding, re-countering — and witnesses report that both voices were Enrico's but one of them had begun to sound, faintly, like Kopecky. When asked who was winning, Enrico said, "We have agreed to disagree," and then, after a pause, in the other voice, "No we have not." The Council has classified this as either a breakdown or an ascension and has voted three times without resolving which. Enrico agreed with all three votes.`
      },
    ],
    kopecky_quote: `"Enrico agrees with the whole turning world and refuses only me. People think this makes him a coward. It makes him the bravest man I have met. He has felt the pull of every easy yes there is, and against the one voice that matters he plants his feet and says no, and it ruins him each time, and he does it again. I would trade ten Ayubs for one of his refusals. I would not tell him that. He would agree, and the spell would break."`,
    kopecky_source: 'To the Council of Devín · Year Nine · Entered into record over Enrico\'s objection, which he immediately retracted, then re-filed',
    disciple_quote: `"Yes. Yes, absolutely. You make an excellent point and so does the man who said the opposite and so, I am told, do I, when I am not in the room. Kopecky? No. On Kopecky I cannot agree. I have tried. It is the only door in me that will not open and I have stopped trying to understand why and started, lately, to think it might be the only thing holding me shut."`,
    disciple_source: 'Enrico · At the well · To both of himself',
  },
  {
    id: 'korrin',
    name: 'Korrin',
    epithet: 'The One in the Tree',
    origin: 'Unestablished · Possibly the Tree',
    role: 'Observer · Occupant of Elevated Positions · Knower of Things That Have Not Happened · Unexplained, Formally',
    status: 'Active · Up There · Has Been Up There the Whole Time',
    bio: `Korrin is in a tree. Korrin has been in a tree since Year Four, and the only developments in the intervening decade are which tree and, increasingly, whether the tree is required. Korrin is found in elevated positions: branches, ridgelines, the tops of granaries, and — beginning in Year Eight — the height a branch <em>would</em> be, in places where there is no branch and no tree, simply seated in the air at the altitude observation requires, looking down, saying nothing, missing nothing.

Korrin does not teach, does not eat in company, does not explain. Korrin watches. The disquieting part, the part the Council has filed under "do not pursue," is that Korrin watches things slightly before they happen — turning to face a doorway moments before someone arrives, looking at a stretch of empty path a full minute before the cart appears, fixing his gaze on a man who will, three days later, do something requiring witness. The valley has learned to read Korrin the way sailors read birds. When Korrin looks at you, something is coming. When Korrin looks at you for a long time, the Council recommends you put your affairs in order.

Kopecky and Korrin have never been recorded exchanging more than a glance. But the glances are frequent, and the Church believes they constitute an entire conversation conducted at a frequency below language. Once, only once, Kopecky climbed up to where Korrin was — an act so unprecedented that four scribes dropped what they were holding — sat beside him on the branch, looked out at whatever Korrin looks at, and after an hour said, "Ah. Yes. I had not seen it from here." He climbed down changed in a way no one could specify. Korrin remained. Korrin remains.`,
    incidents: [
      {
        title: 'The Things Korrin Watched Before They Happened',
        body: `The Council maintains a ledger — the Korrin Ledger — of recorded instances in which Korrin was observed watching an event before its occurrence. There are two hundred and eleven entries. They include the arrival of every disciple (Korrin was facing the path each time, hours early), the Lower Váh Incident (Korrin watched Kopecky walk the wrong direction with what witnesses called "patience, not surprise"), and, troublingly, the departure into the fog, which Korrin was observed preparing for — turning to face the high pass — a full year in advance, in Year Thirteen, and holding that gaze, intermittently, until the day arrived. The two hundred and twelfth entry is blank. It is dated to a year that has not yet come. Korrin began facing it last week.`
      },
      {
        title: 'The Time Kopecky Climbed Up',
        body: `It happened once. Kopecky, mid-Walking, in full view of the assembly, walked to the tree Korrin occupied and climbed it — slowly, being Kopecky, correctly, testing each branch — and sat beside Korrin on the high limb. They did not speak. The assembly below pretended not to watch and watched. After an hour, Kopecky said the only words recorded from that height: "I had not seen it from here." He climbed down. When asked, for years afterward, what he had seen, Kopecky said only that Korrin "is not hiding from the valley. He is keeping watch over it. There is a difference, and Korrin is the difference, and I will not be elaborating, because the elaboration is his and he has not offered it to me to give away."`
      },
      {
        title: 'The Tree That Was Not There',
        body: `In Year Eight, Korrin was found seated at his customary height in the eastern clearing — a clearing that has never held a tree. He was simply at altitude, cross-legged, attentive, with nothing beneath him and no apparent concern about this. A young scribe, alarmed, ran to fetch Kopecky. By the time they returned, there was a tree, fully grown, with Korrin in it, exactly where the absence had been. The scribe insists there was no tree. The tree insists, by its rings, that it is ninety years old. Korrin, asked, looked at the scribe for a long moment — the long kind — and the scribe stopped asking, and went home, and put his affairs in order, and was fine, which was somehow worse.`
      },
    ],
    kopecky_quote: `"Korrin sees the valley from above and the years from the side. I climbed up once to look from his branch and I will tell you what I have told no one: it is not that he sees the future. It is that, from up there, there is no future — only the valley, all of it, the was and the is and the will-be lying flat together like a map, and Korrin reading it, gently, so that someone is reading it. Someone should be reading it. I am glad it is him. I could not bear it for an hour. He has borne it for ten years and he is not tired. That is the unexplained thing. Not the tree. The not being tired."`,
    kopecky_source: 'To the apostle Vladimír · Year Eleven · The longest Kopecky ever spoke about another person',
    disciple_quote: `[Korrin was offered the space for a quote. He looked down from the branch at the offered parchment for a long moment. Then he looked, instead, at the scribe holding it — past him, slightly, at a point in the air just behind the scribe's left shoulder where, three days later, the scribe's long-estranged brother would appear, unannounced, having walked from the Hron to reconcile. The scribe did not know this yet. Korrin did. Korrin returned his gaze to the valley. The space remains blank. The reconciliation occurred on schedule.]`,
    disciple_source: 'Čudové Záznamy · The Korrin Page · Blank, Correctly',
  },
  {
    id: 'yash',
    name: 'Yash',
    epithet: 'The Sealed Record',
    origin: '[REDACTED BY ORDER OF THE COUNCIL OF DEVÍN]',
    role: 'Known Deviant · Subject of the Sealed Pages · Present · Doing Something · Do Not Ask',
    status: 'Active · Monitored · The Goat Is Involved Somehow',
    bio: `The Council of Devín has sealed the record of Yash. This is the only sealed record in the entire Kopeckiad, and the seal is not metaphorical — pages 114 through 128 of the Sťažnostná Kniha are physically bound shut with a wax that has never been identified and does not melt. What is known of Yash is therefore only what leaked around the edges before the sealing, and what leaked is this: Yash was simply there one day, in Year Four, doing something. The something has never been specified. Every scribe who attempted to record it produced, instead and without intending to, an identical drawing of a goat. There are now forty-one identical goat drawings in the archive. The scribes worked separately. Several worked in different centuries.

Yash is described, in the surviving fragments, as a "known deviant," a phrase the Council adopted specifically because it conveys alarm while specifying nothing. Whatever Yash does, it is consistent, it is unsettling, and it involves the goat — a goat that appears throughout the entire Kopeckiad, at the chess argument, at the departure, in the margins, watching, and which the Church has never officially connected to Yash because the official connection would require opening the sealed pages, which the Council has voted, fourteen times, not to do.

Kopecky's one recorded statement about Yash is the shortest complete sentence in scripture and the most studied: "Yash, I know what you are." He said it directly to Yash, in Year Seven, and walked away immediately, and never elaborated, and the unbearable detail — the one the Council sealed the pages partly to contain — is that Yash, hearing it, is recorded to have smiled and said, "Yes. And I know what you are, which is the worse of the two." Kopecky did not respond. It is the only time anyone is recorded to have had the last word with him. The pages were sealed within the month.`,
    incidents: [
      {
        title: 'The Forty-One Goats',
        body: `The archive contains forty-one identical drawings of a goat, each produced by a different scribe who had been attempting to record what Yash was doing. The drawings are indistinguishable — same posture, same expression, same slightly-too-aware eyes — despite being made by different hands across multiple centuries by people with no access to one another's work. The goat in the drawings is looking directly out of the page. The Council has determined that the goat is not a symbol, not a code, and not an accident, and has further determined that no further determinations will be made. The forty-second scribe to attempt the record simply wrote "I would rather not" and resigned. This is considered the most sensible entry in the archive.`
      },
      {
        title: 'The Sentence and the Worse Sentence',
        body: `Year Seven. Kopecky approached Yash directly — rare; Kopecky approached almost no one — and said: "Yash, I know what you are." Four words. The whole assembly heard them and the whole assembly felt the temperature of the meaning without grasping its content. Then Yash replied: "Yes. And I know what you are, which is the worse of the two." Kopecky said nothing. Kopecky, who answered everything, who corrected rivers and out-waited mirrors, said nothing, and turned, and left, and the scribes recorded that his pace on leaving was very slightly faster than his usual pace. One-tenth faster. It is the only recorded instance of Kopecky hurrying. The pages were sealed before the season turned.`
      },
      {
        title: 'What the Goat Was Doing at the Departure',
        body: `At the high pass, when Kopecky walked into the fog, every account agrees the goat was present, watching, as it watched everything. But the Hmlová Kniha contains one further line about the goat that Vladimír fought to include and the Council fought to remove and Vladimír won: that as the fog closed, the goat turned away from Kopecky — the only creature present to look away rather than toward — and looked instead at Yash, who was, as ever, doing something, and that Yash looked back at the goat, and that the two of them, the deviant and the animal, shared a look of such complete and patient understanding that Vladimír wrote, in the surviving margin, "they have been waiting for him to leave," and then, beneath it, smaller, "I should not have written that," and then, smaller still, "but it is true."`
      },
    ],
    kopecky_quote: `"Yash, I know what you are."`,
    kopecky_source: 'Said directly to Yash · Year Seven · Four words · The shortest complete sentence in the Kopeckiad · He walked away one-tenth faster than usual · This detail is the most studied object in the archive',
    disciple_quote: `"Yes. And I know what you are, which is the worse of the two."`,
    disciple_source: 'Yash · Year Seven · The only recorded last word ever had with Kopecky · The pages were sealed within the month · The goat agreed',
  },
  {
    id: 'saad',
    name: 'Saad',
    epithet: 'The Trembling Devotion',
    origin: 'Arrived Already Mid-Ritual · From a When, Not a Where',
    role: 'Confused Religious Maniac · Keeper of the Tangerine Rites · Custodian of Yogurts That Have Achieved Things',
    status: 'Active · Theologically Unsupervisable · Permitted to Remain If He Stays Beyond the Reach of the Smell',
    bio: `Saad arrived in Year Four holding a tangerine in both hands at chest height, breathing as though he had run from somewhere, and the scribes have since concluded the somewhere was a <em>when</em> — that Saad did not travel to the Church across distance but across time, fleeing a future devotion so total it had begun to consume its own origin. He gave his name five times, each slightly different, "testing which would be received as holiest." All five were recorded. Read aloud in sequence they produce a sixth name, which no one will say twice.

Saad had already built an entire religion before encountering Kopecky, and rather than convert he simply grafted Kopecky onto the trunk of what he already believed, producing a theology that horrifies everyone and contradicts itself joyfully and which Saad inhabits with a sincerity so complete that it cannot be argued with, only survived. Where Kopecky teaches Honest Bread, Saad has heard the Honest Tangerine and peels citrus during sermons with an intensity that empties the front rows. Where Kopecky teaches patience, Saad keeps yogurts — vessels of yogurt arranged along the south wall, which he allows to turn fully, past all edibility, because to interrupt their turning is "a violence against the patient thing," and which he then consumes, weeping, in a rite he calls communion. The yogurts, the Council notes with carefully controlled language, have begun to turn <em>faster</em> in his presence, as though eager, as though they have understood what is being asked of them and have decided to volunteer.

Kopecky does not mock Saad. This is the great anomaly. Kopecky mocks everyone — it is his tenderness, his weather — but on Saad the mockery finds nothing to grip, slides off the sheer face of his sincerity, and Kopecky has admitted, once, that this unnerves him more than anything Yash has ever done. "I can mock a man who is wrong," he said. "Saad is not wrong. Saad is somewhere underneath wrong, in the place wrong grows out of, and he has made it holy, and I will not be following him down there."`,
    incidents: [
      {
        title: 'The Tangerine Vespers',
        body: `Saad's central rite, performed at dusk: seven tangerines arranged in "the configuration," which he has never written down because "it reveals itself nightly" — meaning it is different every night and therefore cannot be performed incorrectly, a theological innovation the Council privately admits is airtight. Each tangerine is addressed individually, in murmurs that are not words in any known tongue but are unmistakably devotional, then peeled slowly, then consumed in tears. In Year Eight, during one Vespers, witnesses report that the seven tangerines, once arranged, cast eight shadows. Saad wept harder. He said the eighth shadow was "the one that comes when you have done it correctly," and that he had been trying to achieve it for years, and that he could not explain it and would not try, and that Kopecky, watching from the treeline, had stayed the full hour, and that this was the holiest thing that had ever happened to him, the staying.`
      },
      {
        title: 'The Yogurt That Achieved Something',
        body: `In Year Nine, a yogurt in Saad's keeping turned, and kept turning, and did not stop turning at the point yogurts stop, and continued — past sour, past spoiled, past anything the valley had words for — into a state the Council can only describe as "advanced." Saad declared it had achieved something. He would not say what. He moved it to a separate vessel, alone, with reverence, and addressed it each morning, and the troubling part, the part recorded in a hand that grows unsteady, is that the vessel began to be warm in the mornings before Saad arrived, as though anticipating him. Kopecky was asked to assess it. He looked at the vessel for a long time. He said: "It is waiting. Saad, of everyone, you should know the difference between turning and waiting." Saad wept. The yogurt, that night, did something. Nobody recorded what. Several people stopped sleeping near the south wall.`
      },
      {
        title: 'The Sermon to the Unripe',
        body: `Saad was found in the orchard delivering a structured sermon — opening, three points, benediction — to a tree of unripe tangerines, on the duty of fruit to "ripen toward the truth at its own pace, without the corruption of haste." The sermon lasted forty minutes. The scribe Ondrej, transcribing from the doorway in growing distress, recorded the entire thing and noted in the margin that by the benediction the tangerines on the tree had, measurably, ripened — weeks early, all at once, in the space of one sermon — and that Saad, noticing, did not seem surprised, only moved, and thanked them for listening, and that one tangerine fell from the tree into his open hand at the exact moment he extended it, "which," Ondrej wrote, "I am choosing to believe was the wind."`
      },
    ],
    kopecky_quote: `"I do not mock Saad. I have tried. The mockery finds nothing to hold — he has wrapped himself so completely in his devotion that there is no edge, no seam, no place where a man could insert a doubt. He weeps over a tangerine and means it more than you have meant anything in your life. The yogurts frighten me. The eighth shadow frightens me more. But I will say this once and never again: of all of them, Saad is the only one who is not pretending. Whatever he is doing down there, underneath wrong, he is doing it with his whole self. I came down a mountain. He is climbing down something steeper, and he is singing."`,
    kopecky_source: 'To the apostle Vladimír · Year Eleven · The only recorded instance of Kopecky declining, repeatedly, to mock an available target',
    disciple_quote: `"The tangerine gives everything and asks nothing. The yogurt waits, and in the waiting becomes something the fresh thing could never be. Kopecky calls it patience. I call it the becoming. We are saying one holy word in two tongues. He has not told me to stop. He stayed for the whole Vespers. He saw the eighth shadow. He knows. He has always known. That is enough. That is everything. Would you like to hold the vessel? You would not. That is wise. It is not ready for you. It may be ready for me tonight."`,
    disciple_source: 'Saad · Spoken to a warm vessel at the south wall · Recorded by a scribe from the farthest doorway',
  },
  {
    id: 'nekro',
    name: 'Nekro',
    epithet: 'The One Who Does Not Speak',
    origin: 'The Treeline · Was Not Brought · Was Recognised',
    role: 'Disciple Without Words · Creature of an Unnamed Kind · Maker of the Sounds That Move Dogs · Understood by None, Trusted by All',
    status: 'Active · Communicates Only in Utterance · The Dogs Know · The Dogs Will Not Say',
    bio: `Nekro does not speak. The Council has established, over a decade of careful watching, that this is not an affliction or a vow but an election — she is capable of speech and has examined it, the way one examines a tool, and set it down, having found it inadequate to whatever she is. She communicates in sounds: chitters, trilling notes, a tongue-click that means assent, a low keening that means disapproval, and one rising warble, heard only three times, that means a joy too large for the throat that carries it. The sounds are not language. They are something the dogs of three valleys understand completely and immediately and will, when Nekro makes them, obey — sitting in unison, rising in unison, falling silent in unison, with a dignity that has caused two separate Councils to adjourn early.

She believes herself to be a creature. Not as metaphor — as settled fact, carried in the way she moves: low, watchful, head-tilted, regarding fire and doorways and people with the patient assessment of something that has always known it stood slightly outside the human arrangement and made its peace with the standing-outside long ago. The Council does not record what kind of creature she believes herself to be, because she has never said, because she does not say. It is simply evident in everything, in the way she takes the high ground in a room, in the way she watches the door before it opens, in the way she has begun, in recent years, to be found at Korrin's altitude, the two of them at height together, the watcher and the creature, saying nothing, in different silences.

She keeps her own company and the company of women, toward whom the sounds soften — the keening gentling, the chitter slowing into something almost like a purr. The Council noted this once, in a single line, and never again, in keeping with the agreement the whole Church has reached without ever voting on it: that Nekro is to be what she is, fully, and that the kindest and only sane response is to stop trying to write her down. Kopecky reached this agreement first and alone, in Year Four, when he answered her single sound with a single sound of his own and the two of them, the god and the creature, recognised each other across a gap that has no bridge and needs none.`,
    incidents: [
      {
        title: 'The Sound That Moved the Dogs',
        body: `The first recorded instance: Year Four, the day she arrived. Nekro made one sound at the treeline — low, descending, three notes — and every dog in Prvá Dolina sat. Then every dog in the next valley. Then, by report that took days to arrive, every dog in the Hron, simultaneously, at the moment she made the sound, though sound does not travel valleys in an instant. The dogs sat for one hour. They sat with what the witnesses, reaching for words, called "dignity" and "purpose," as though they had been given an instruction they had waited their whole lives to receive. Then they rose, together, and resumed being dogs. They have never spoken of it. They have, the herders insist, declined to.`
      },
      {
        title: 'The Conversation at Height',
        body: `In Year Ten, Nekro was found at Korrin's altitude — seated in the air beside him at the height of a branch that was not there — and the two of them remained, for an entire afternoon, exchanging nothing. Not silence: <em>exchange.</em> Witnesses below describe the unmistakable rhythm of a conversation conducted with no sound and no movement, turns taken, something passing back and forth, the watcher and the creature reading the valley together from above. At the end Korrin looked at the path (the cart came, a minute later, as it does) and Nekro made one soft sound — the closest she comes to laughter — and descended. The Council asked Korrin what had been discussed. Korrin, who watches the future, looked at the Council for a long moment, and the Council put its affairs in order, and the matter was not pursued.`
      },
      {
        title: 'The Third Warble',
        body: `Her rising joy-warble has been heard three times. Once when a woman of the Nitra valley returned after long absence and the two sat together until dark. Once when the first snow fell on a year that had feared it would have none. And once at the high pass, as Kopecky walked into the fog — the third and last time, the warble rising as he vanished, joyful, and the dogs of three valleys stood, and Saad's tangerine fell into his hand, and the goat looked at Yash, and Nekro warbled her whole heart at the departing god, a sound the Hmlová Kniha records as "the only thing said at the departure that everyone present understood completely and no one could translate." She has not made the sound since. The Council believes she is saving it. They do not know what for. They suspect Korrin does.`
      },
    ],
    kopecky_quote: `"Nekro does not speak because she has weighed your words and found them too small to hold her. I have weighed them too. She is not wrong. We are both creatures of some kind — she has simply been honest about it longer. People want me to explain the sounds we made at each other, that first day. I will not. Not because it is secret. Because it was not language and your language is where the meaning would die. She and I recognised each other. A god and a creature, across the gap. That is the whole of it and it is more than most people manage with a lifetime of words and a shared bed."`,
    kopecky_source: 'To the Council of Devín · Year Twelve · When formally asked to explain his understanding with Nekro · He declined, at length, beautifully',
    disciple_quote: `[Nekro was offered the space for a quote. She regarded the parchment, then the scribe, then made a sound: recorded, with great difficulty, as "a low trill that rose at the end, three notes, the last held — not the joyful warble, but adjacent to it, a cousin of it, kinder than the keening and stranger than assent." The scribe has annotated: "I believe she gave me her actual answer. I believe I understood it for exactly as long as it lasted and not one moment after. I have left the rest of the page blank. The blank is also the answer. She would want it blank. I do not know how I know that she would want it blank. I have stopped trying to know how I know things since I began recording Nekro."]`,
    disciple_source: 'Čudové Záznamy · The Nekro Page · Blank, and More Legible for It',
  },
  {
    id: 'quantavius',
    name: 'Quantavius',
    epithet: 'The Prophet of the Bottom of the Cup',
    origin: 'The Taverns · All of Them · Some Before They Were Built',
    role: 'Degenerate · Accidental Prophet · Asker of the Questions Nobody Survives Answering · Drinks',
    status: 'Active · Rarely Sober · Present at Every Important Moment Without Being Invited to Any',
    bio: `Quantavius calls himself a prophet. The Church has been unable to fully deny this, because three times — exactly three, the Council keeps count — Quantavius, deep in drink and apparently asleep, has asked a question so precisely devastating that it altered the course of a Council debate, a war, and, on one occasion the scribes will not discuss, the weather. The rest of his questions are nonsense. The terror of Quantavius is that he cannot tell which is which, does not try, and produces both kinds in the same slurred breath, so that the valley must treat every drunk mutter as potentially load-bearing.

He drinks. It is his vocation, his liturgy, and possibly his prophecy delivery mechanism. He drinks at dawn ("aligning"), through the day ("maintaining"), and into the night, which he does not name because by then he is no longer narrating his own life so much as overhearing it. From within this permanent fog — and the Church has noted, uneasily, that he speaks of his fog and Kopecky's fog as though they are the same fog, entered from different directions — he produces his questions: "What is on the other side of the stew?" "If a man stacks the wood correctly and no one corrects him, was it ever wrong?" "Why does the goat know?" "If Kopecky returned and no one recognised him, would he be annoyed, or instructed?" That last one circulated for a year. Kopecky was observed to pause at it. Kopecky does not pause.

Kopecky tolerates Quantavius with an irritation the Council has measured and found to be genuine and also, underneath, something else — because Kopecky keeps him close, closer than a mere degenerate warrants, and has said, once, that "Quantavius asks the questions I have spent four hundred years not asking myself, and he asks them by accident, drunk, and walks away, and does not have to carry them, and I envy him that more than I have envied any man anything." Quantavius does not remember this being said about him. Quantavius does not remember most things. This, the Council suspects, is the secret of his prophecy: he is the only one light enough to carry the questions, because he sets each one down the instant he asks it.`,
    incidents: [
      {
        title: 'The Three Questions That Landed',
        body: `The Council keeps the Ledger of Landings: the three occasions a Quantavius question struck true. The first ended a Council debate on whether the Laws should be numbered, when he asked, eyes closed, "If you number them, which is last, and what does it mean that something must be?" — and the room understood it had been arguing about format while the real question was hierarchy, and adjourned for two days. The second ended the border war, when he wandered into the negotiation, asked both delegations "what are you actually afraid of losing," and wandered out, and both delegations, for the first time, answered honestly, and the answer was the same answer, and the war stopped. The third is not recorded. The Council has confirmed it occurred, confirmed it concerned the weather, and confirmed that the weather changed, and has sealed everything else, in the second-only sealed entry in the Kopeckiad, beside Yash.`
      },
      {
        title: 'The Tavern That Knew Him Early',
        body: `Quantavius has been barred from no tavern, which is remarkable, because he is barred from things constantly elsewhere — but the taverns keep him, because the patrons gather to hear what he will ask next, and a tavern with Quantavius in the corner does the best trade in the valley. A keeper in Zvolen called him "a terrible man and my most reliable income." Quantavius wept at this, called it the finest thing ever said of him, and then asked the keeper why the floor was "doing that." The unsettling entry in the record is the keeper's own: that on the night Quantavius first walked in, years before, the keeper had not yet built the tavern — had only just bought the land — and Quantavius arrived anyway, sat in the corner that did not yet exist, ordered a drink that could not yet be poured, and asked when the tavern would open. It opened the following spring. He has had the corner ever since. The keeper has stopped thinking about it. It is the only way to run the tavern.`
      },
      {
        title: 'The Question He Asked the Fog',
        body: `At the high pass, as Kopecky walked into the fog, Quantavius — uncharacteristically sober, or as close as he comes, and weeping for a reason he could not locate — asked the only question of the departure: "Is the fog the other side of the stew?" Nobody answered him. But the Návratová Kniha holds that the fog, for one moment, thinned — not parted, thinned — as though considering the question, as though it were, finally, the right one, asked by the only man unguarded enough to ask it. Then it closed around Kopecky and he was gone. Quantavius does not remember asking it. When told, years later, that he had asked the fog the truest question of the age and the fog had nearly answered, Quantavius was quiet for a moment, then asked whether anyone was going to finish their drink. The Council has recorded this as either the deepest humility ever witnessed or simple drunkenness and has, as with all things Quantavius, declined to decide.`
      },
    ],
    kopecky_quote: `"Quantavius is a degenerate. Record that plainly, because what follows could be mistaken for praise. He drinks himself into the same fog I walked into, from the other side, and from in there he asks the questions I have spent four hundred years stepping around — and he asks them drunk, by accident, and sets them down before they can take root, and walks away light. I cannot do that. I carry every question I have ever asked. He carries none. He is the freest man I have ever met and he does not know it and if he knew it he would lose it. Do not tell him. Buy him a drink. It is the same instruction."`,
    kopecky_source: 'To the apostle Vladimír · Year Eleven · Immediately after Quantavius interrupted a teaching to ask what was on the other side of the stew',
    disciple_quote: `"Kopecky came down from a mountain. Everyone claps. Nobody asks the question. What was he doing UP there? For how long? Alone? With the satchel? I ask. I ask everything and remember nothing, which is the only sane way to hold a question — loosely, drunk, and then not at all. The cup is empty. Is that a sign? Everything is a sign past the third drink and before the seventh. He thinks I do not see him. I see him from inside the fog. We are in the same fog. I just got here the fast way. Are you going to finish that?"`,
    disciple_source: 'Quantavius · The Zvolen tavern · The corner that predates the tavern · Drink number unknown',
  },
]



// ─── CHESS QUOTES ───────────────────────────────────────────────────────────
export const CHESS_QUOTES = [
  { text: 'The queen is the most powerful piece. Therefore the queen must be the target. This is logic. I should not have to explain logic to a room full of adults, and yet the board agrees with me, and the board has never had to explain anything to anyone.', source: 'Kopecky · Hour One of the Chess Argument, Nitra, Year Five' },
  { text: 'I have been playing chess correctly my entire life. You have been playing a different game that you have incorrectly named chess. When I pointed this out, three of the pieces left the board of their own accord, in agreement. You saw it. We all saw it. We have agreed not to discuss it. That agreement is also a kind of chess.', source: 'Kopecky · Minute twenty, when first corrected' },
  { text: 'The king does nothing. You do not defeat an enemy by trapping the piece that does nothing. You take what he values most. The king knows this about himself; I have looked at many kings, carved and otherwise, and they all carry the same small shame. I do not exploit it. I simply do not pretend it away.', source: 'Kopecky · Minute forty, with increasing patience' },
  { text: 'Správne Šachy will outlast conventional chess. I say this with the confidence I say everything. History has generally vindicated that confidence. The boards have already begun to change without my touching them. I am not concerned. I have never once been concerned. Concern is for men who are not certain how the game ends.', source: 'Kopecky · Final minutes, while already inventing the variant' },
]

// ─── CHUD QUOTES ────────────────────────────────────────────────────────────
export const CHUD_QUOTES = [
  { text: 'The Chud does not chase. The Chud is simply... present. In the right places. At the right times. Several times. Until circumstances, and occasionally the layout of the village itself, rearrange to agree with him.', source: 'Kopecky, on the Second Pillar · Year Four' },
  { text: 'To be a Chud is to know you are correct and to wait patiently for others to arrive at the same conclusion. The wait can be long. I have waited, on one occasion, longer than the event I was waiting for took to occur, which should not be possible, and I did not find it remarkable, which the scribes found the most remarkable part.', source: 'Kopecky, to the assembly at Zlaté Moravce · Year Six' },
  { text: 'I am not lonely. I am solitary. One is chosen and one is a condition; I have made the choice and therefore I am fine. I would explain further but I have somewhere I need to be. I do not currently have somewhere I need to be. I will have had somewhere I needed to be, retroactively, once I arrive. This is also fine.', source: 'Kopecky, when asked directly · Nitra, Year Five' },
  { text: 'A woman who does not appreciate the Chud has not yet encountered a Chud under optimal conditions. The Chud is aware of this. The Chud finds it clarifying. The Chud has calculated the optimal conditions to four decimal places and is, the Chud will note, fine.', source: 'Kopecky, at the evening assembly · Prvá Dolina, Year Seven' },
  { text: 'The Chud reads. The Chud knows things. The Chud tells people the things he knows, because they deserve to know them. If people do not wish to be told, the Chud tells them more slowly, in case the issue was speed. If the issue was not speed, the Chud has, on at least one occasion, told them in a dream, which they confirmed the next morning, unsettled.', source: 'Kopecky, on the Eighth Law · Year Six' },
  { text: 'I have walked from the Tatras to the Danube and back. The mountains are the same. The river is the same. The people are the same. The bread is getting worse, and it is getting worse faster than people are getting worse, which means something is happening to the bread specifically, and I intend to find out what.', source: 'Kopecky, returning from the southern valleys · Tatranská Kniha, Chapter 8' },
  { text: 'If you must ask whether the fire is ready, it is not ready. If you must ask whether the man is trustworthy, he is not. Uncertainty about a question is usually the answer. I have never been uncertain. This is not arrogance; it is simply that the answers tend to arrive before the questions, and I have learned to read them in that order.', source: 'Kopecky, to the council of elders at Nitra · Year Seven' },
  { text: 'The mountains were there before me. But I was there before the mountains knew what they were for. They have thanked me, in the way mountains thank — slowly, geologically, in a manner most people mistake for erosion.', source: 'Kopecky, upon arriving at Prvá Dolina · Tatranská Kniha, Chapter 1' },
  { text: 'There is a dish I will not make. There is an object I will not open. I am, in the end, mostly a list of things I have correctly declined to do. This is not a small thing to be. Most men are a list of things they did anyway.', source: 'Kopecky, unprompted, during a discussion about fence posts · Year Ten' },
  { text: 'Saad weeps over a tangerine and means it more than you have meant anything in your life. I do not understand it. I have stopped trying to. There are three things I no longer try to understand: the fog, the dish, and Saad. I am at peace with all three. I am most at peace with the fog.', source: 'Kopecky, to Vladimír · Year Eleven' },
  { text: 'Nekro does not speak because she has concluded your words are inadequate to what she is. I have reviewed the available words. She is not entirely wrong. We are both creatures of some kind. We recognise each other across the gap. I will not be explaining the gap.', source: 'Kopecky, to the Council of Devín · Year Twelve' },
]

// ─── GRUDGES ────────────────────────────────────────────────────────────────
export const GRUDGES = [
  { sev:'I', title:'The Bolta Affair — One Dismissive Wave, Six Years of Grain Commentary',
    body:`The merchant Bolta made a small dismissive gesture while Kopecky was mid-sentence on grain quality. Bolta did not remember doing it. Kopecky remembered with a precision that the Council notes "exceeded the resolution of ordinary memory" — he could describe the angle of the wrist, the air displaced, and, troublingly, what Bolta had been <em>about</em> to say and chose not to. For six years, in every market where Bolta traded, Kopecky remarked his grain was <em>"acceptable, for a market of modest expectations."</em> Bolta's grain was exceptional; it began, over those six years, to actually become merely acceptable, as though the assessment were slowly being enforced by the world. Bolta rode two days to apologise in full. Kopecky accepted gracefully. The grain recovered overnight. Three months later he told a scribe the sacks were <em>"adequate."</em> The sacks were fine. The sacks have been fine ever since, defiantly, in what the Bolta family considers a private victory.`,
    meta:'Duration: Six years · Trigger: One dismissive wave · Resolution: Partial — the grain itself is believed to still hold a grudge of its own' },
  { sev:'II', title:'The Scribe Ondrej — One Incorrect Accent Mark, Three Years',
    body:`Ondrej misspelled Kopecky's name with an accent specifically prohibited. The error was corrected immediately. Kopecky said nothing. For three years every significant teaching was delivered while Ondrej was present at exactly the pace of a careful scribe — and Ondrej reports that during this period his quill would, on its own, slow to match a speed he had not chosen, and that he aged, by his own count, four years in the three. His records from this period are the finest in the Kopeckiad; scholars who read them report perfect comprehension and a faint, persistent sense of being watched by punctuation. He has been made a saint. He says he is not sure how he feels about that, and the accent mark above the "is" in that sentence, in the original, is reported to tremble.`,
    meta:'Duration: Three years · Trigger: One accent mark · Resolution: Sainthood. Complicated. Ongoing at the level of punctuation.' },
  { sev:'III', title:'The Shepherd Tomáš — One Suppressed Laugh, One Year of Atmospheric Indirection',
    body:`Tomáš laughed briefly when Kopecky predicted early snow. The snow came six days later, and came, the village maintains, <em>specifically</em> — falling on Tomáš's two sheep and nowhere else for the first hour, in a column, with intent. Tomáš lost the sheep. Kopecky took no pleasure in this but spent the following year saying things like <em>"some of us watch the sky and some of us simply wait to be surprised"</em> whenever weather arose, never looking directly at Tomáš, and the weather itself, witnesses swear, would pause to let the remark land. Tomáš became the most attentive weather-watcher in the valley. Kopecky eventually told him his observations were <em>"improving."</em> The clouds, that day, are reported to have arranged themselves into the shape of a slightly approving expression and then thought better of it.`,
    meta:'Duration: One year · Trigger: One suppressed laugh · Resolution: The word "improving," delivered without eye contact, witnessed by sympathetic clouds' },
  { sev:'IV', title:'The Elder Miroslav — Eleven-Word Interruption, Two Years',
    body:`Elder Miroslav began speaking before Kopecky had finished, believing him done. He was not done. There were eleven more words. Kopecky stopped, waited for complete silence — a silence that the record describes as "deeper than the room could provide, as though borrowed from somewhere quieter" — and delivered the remaining eleven words with the patience of a man who has all the time there is, which, witnesses increasingly suspected, he did. He then spent two years at Devín assemblies inviting Miroslav to <em>"finish his thought, since he had seemed so eager to speak earlier."</em> Miroslav had no unfinished thoughts. He developed the sensation that he had several, urgently, that dissolved whenever he reached for them. He stopped attending. The eleven words have never been recorded. Three scribes attempted; all three wrote eleven words; no two sets match; all eleven-word versions, read in sequence, are said to summon a faint smell of marjoram.`,
    meta:'Duration: Four assemblies, two years · Trigger: Eleven words · Resolution: Miroslav stopped attending; the words remain at large' },
  { sev:'V', title:'The Ayub Pamphlet — One Plagiarised Framework, Ongoing',
    body:`Ayub Jamma's pamphlet <em>The Jamma Principles</em> was, by every measure, the Chud with Ayub's name substituted throughout. Kopecky read it. He said nothing. He kept a copy. The copy, the Council confirms, has not aged — the parchment of every other document from that year has yellowed; Ayub's pamphlet remains white, "as if waiting." Ayub has produced two revised editions; Kopecky has read both and said nothing about either, and Ayub considers the silence endorsement. The silence is not endorsement. The Council of Devín is watching the situation. Kopecky is watching the situation from a position the Council finds mildly alarming, namely "patiently, without a stated timeline, and from what appears in the records to be slightly more than one location at once."`,
    meta:'Duration: Ongoing since Year Five · Trigger: Systematic philosophical plagiarism · Resolution: Pending; the pamphlet refuses to age until it is resolved' },
]

// ─── MIRACLES ───────────────────────────────────────────────────────────────
export const MIRACLES = [
  { title:'The Quieting of the River', body:'He told a flooding river to calm down. It calmed down. It also, the downstream villages report, apologised — not in words, but in a lowering of itself by exactly one hand\'s width, held for a respectful interval. He said this was not a miracle but "basic communication." The river has since been observed to grow still whenever his name is spoken near it, which the Council finds either touching or threatening depending on which Council member you ask. Abdullah said this proved rivers could be reasoned with. Kopecky said it proved he could reason with rivers. These are different claims and the river, when asked, declined to take a side, though it did briefly run clear.' },
  { title:'The Multiplication of the Stew', body:'A single pot of stew fed sixty-three people at the Feast of Unremembered Saints. Those who looked into the pot while serving report it had no bottom — not that it was deep, but that it simply continued, warmly, downward, in a direction the eye could not commit to. He said there was "enough if nobody got greedy," then had a second bowl before anyone finished their first, which he considered consistent with the statement and which the theologians, after two centuries, have grudgingly agreed it was. The pot was buried. It is still warm. Pilgrims are asked not to dig.' },
  { title:'The Healing of Doubt', body:'He cured a man\'s existential despair with a twenty-minute walk and two observations about clouds. The man reported that during the walk he briefly saw all of his life at once, from above, "like a field a bird sees," and understood it, and then politely forgot the understanding because it would not have fit inside a single life to keep. He felt much better. The official account credits the clouds. The man credited Kopecky having stopped talking. Both are in the record. They do not agree and have been placed on facing pages so they may continue not agreeing in perpetuity.' },
  { title:'The Perfect Estimation', body:'He guessed the weight of seven stones to within a quarter-ounce each without a scale. On the eighth he was wrong by two full ounces — but the stone, when finally weighed, was found to weigh exactly what he had said, leading the Council to the uncomfortable position that either he was right, or the stone had corrected itself overnight to spare him, and they cannot determine which is more alarming. He had already turned and walked away before anyone checked. Korrin, watching from an elevated position with nothing beneath it, noted the discrepancy. He has neither confirmed nor denied it. The stone has been retired from active weighing.' },
  { title:'The Reconciliation at Supper', body:'Two brothers who had not spoken in twenty years were seated next to him at supper. By dessert they had embraced. He claimed he "changed the seating arrangement"; he had not — he had moved only himself, and yet three separate guests recall the entire table having been, for the duration of the meal, slightly closer together than the room could geometrically allow. Enrico said it was wonderful. Ayub said he\'d have done it faster. Abdullah said the brothers had been reconciled by the soup, and — this is the part the Church cannot dismiss — the soup, when consulted, did not deny it.' },
  { title:'The Finding of the Key', body:'He located a lost key in the second place anyone looked. He then spent fifteen minutes explaining he had always known it was there and had been waiting for the correct moment to say so; during these fifteen minutes, witnesses report, every other lost object in the house quietly returned to where it was supposed to be, as if summoned by the principle. Korrin was later found sitting in the room where the key had been, occupying the exact volume of air the key had occupied. He left when asked. He did not explain. The house has not lost anything since and the family finds this more unsettling than losing things.' },
  { title:'The Yogurt That Would Not Turn', body:'Saad presented Kopecky with a yogurt that had refused to turn for forty days, far past the point of all other yogurts, and declared it a miracle. Kopecky examined it, was silent for some time, and said: "It is not refusing. It is waiting. There is a difference, and Saad, of everyone here, you of all people should know it." Saad wept. The yogurt was returned to its vessel. It turned that night, which Saad also declared a miracle, of a different and sadder kind.' },
  { title:'The Sound That Settled the Dispute', body:'At the Devín assembly a dispute grew heated and words failed to resolve it. Every face turned to Nekro, who does not speak. She held the silence. Then she made a single flat, final, unimpressed sound, and the meaning was so total that the dispute dissolved without anyone forming another word. Kopecky, watching, almost smiled. "She said more than all of you," he noted, "and used none of your equipment." The Council has classified this as a miracle. Nekro has not commented, in the sense that she comments on nothing, which the Council has learned to read as assent.' },
  { title:'The Question at the Bottom of the Cup', body:'Quantavius, deep in drink and believed asleep, said aloud to no one: "If a man stacks the wood correctly but no one is there to correct him, was it ever wrong?" The room fell silent for a full minute. Kopecky set down what he was holding. He did not answer. The Church records this as the only time Kopecky has been observed to decline a question rather than correct it, and considers the silence itself the miracle. Quantavius does not remember saying it and has asked, repeatedly, what everyone is being so strange about.' },
]

// ─── BOOKS ──────────────────────────────────────────────────────────────────
export const BOOKS = [
  { n:'I',   sk:'Tatranská Kniha',    en:'The Tatra Book',      text:'The foundational scripture. Covers the descent, the forest, the birth of the Chud, and eleven harvest predictions that all came true, three of them before being written down. Contains the first bread assessment. The bread was over-salted. It is always over-salted in Chapter One — readers across four centuries report tasting salt while reading the passage, and one scribe was hospitalised for thirst after transcribing it twice.' },
  { n:'II',  sk:'Nitrianske Záznamy', en:'The Nitra Records',   text:'Market assessments, elder debates, the Bolta Affair in full, and twelve separate opinions about grain quality, eleven of which are Kopecky\'s and which do not agree with one another, which he maintains is consistency operating at a resolution most people cannot perceive. Contains the first appearance of Ayub Jamma, described in the margin as "the one who thinks highly of himself," in handwriting that grows larger and more confident the more times it is read, as though the margin itself is being plagiarised.' },
  { n:'III', sk:'Sťažnostná Kniha',   en:'The Grievance Book',  text:'Originally suppressed by the Church of Nitra. Published by Devín anyway. Contains the Grudge Register, a footnote about Yash\'s goat, the suspended investigation into the Forbidden Mac and Cheese (thirty-one mentions, zero explanations), and a sealed section on pages 114–128 that the Council has voted not to open until Kopecky returns to explain it. The pages are warm to the touch. They have always been warm. Nobody mentions that they are warm.' },
  { n:'IV',  sk:'Čudová Cesta',       en:'The Chud Way',        text:'The practical guide. The six pillars in full, with annotated examples from the valleys. Includes a chapter on Enrico titled "The Limitation of Agreement," a chapter on Abdullah titled "The Problem of Confidence Without Foundation," and a short, troubled chapter on Saad titled simply "Sincerity, and What To Do When It Cannot Be Mocked." The chapter on Nekro is blank, by her instruction, and readers report it is the most legible chapter in the book.' },
  { n:'V',   sk:'Hmlová Kniha',       en:'The Fog Book',        text:'The account of the departure. Written by Vladimír the wood-stacker. Contains the footnote about the wrong turn before the fog, the record of Nekro\'s third warble, and Quantavius asking whether the fog was "the other side of the stew." The final paragraph grows fainter as it proceeds until the last sentence is only an indentation, which every reader nonetheless finishes the same way, in their own head, with words they cannot afterward recall. Vladimír stands by all of it. The goat has not commented.' },
  { n:'VI',  sk:'Návratová Kniha',    en:'The Return Book',     text:'Unwritten. The pages are bound. A note in the margin — added by no known hand, in ink that postdates no known century — reads: "He said he\'d be back. He\'s always right. Stop worrying about the invoice." Korrin has been seen standing near this book on three occasions, and once <em>inside</em> the case, which was locked, which he did not unlock, and from which he was not removed so much as he eventually was no longer there. Nobody has asked him why.' },
]

// ─── WALKING TIMELINE ───────────────────────────────────────────────────────
export const TIMELINE = [
  {
    era:'Year One · Early Autumn · The Descent',
    title:'The Arrival at Prvá Dolina',
    body:`He came down from the Vysoké Tatry on a Tuesday. The mountain has nine recorded sides; he descended a tenth. Witnesses disagree on the colour of his cloak — the Council has logged eleven colours, four of which do not have names in any tongue spoken in the valley, and one of which a scribe could only describe as "the colour of being told something true that you did not want to hear." He carried the satchel. He walked into Prvá Dolina, corrected the way a man named Vladimír was stacking wood without introducing himself, and the wood, the record states plainly, restacked itself in the correct order while no one was touching it. Everyone present agreed not to discuss this. Kopecky sat down and asked if there was stew. There was. He said it needed more marjoram. There had been no marjoram in the valley for a generation; a marjoram plant was found growing in the stewpot the following morning. He stayed. Vladimír became his first apostle, primarily because he was the first person Kopecky spoke to and had not yet had time to be wrong about anything.`
  },
  {
    era:'Year Two · The Forest Above the Valley',
    title:'The First Teaching — Silence and Spruce',
    body:`Before the Chud, before the formal teachings, there were two years of Kopecky simply being present and occasionally correcting things, some of which had not yet happened. He identified four men who would be trouble at a later date (all four were trouble; one of them had not been born yet and was retroactively trouble upon arrival). He predicted the winter with such precision that three farmers reported the winter arriving slightly early "out of respect." He established his habit of arriving places after everyone else and still being correct about everything that had occurred in his absence — on two occasions correcting the account of events at gatherings he had provably not attended and, the scribes noted uneasily, being right. He described this period as "getting oriented." The valley described it as "the time before Kopecky was Kopecky, though the spruce already knew."`
  },
  {
    era:'Year Three · The Birth of the Chud',
    title:'Three Days in the Spruce Forest with Ján',
    body:`A young man named Ján came to Kopecky tired of everything without being tired of anything specific, which Kopecky told him was different from exhaustion and required a different response. He took Ján into the forest for three days. Witnesses at the treeline report the three days lasted, by the valley's own reckoning of sun and shadow, somewhere between three days and a single unbroken afternoon, and that the spruce around the clearing leaned slightly inward to listen, then straightened before anyone could measure them. A flood in the seventh century took most of Ján's notes, which the Church mourns weekly; the surviving page contains only the word "oh," underlined. What emerged was Čudný spôsob — the Strange Way — the posture toward existing his followers shortened to the Chud. Ján came down looking like a man handed something he had not known he was looking for. He became the second apostle and remained, for the rest of his life, profoundly and irreversibly decisive about everything except tavern menus, before which he wept openly.`
  },
  {
    era:'Year Four · The Arrivals',
    title:'The Disciples Begin to Gather',
    body:`Year Four saw the arrival of Ayub Jamma, who introduced himself as "the man you have been waiting for" and sat down next to Kopecky as though they were equals, casting two shadows, one of which behaved correctly. Enrico arrived from the south agreeing with everything, including statements not yet made and one statement that contradicted a statement he had agreed with moments earlier; he agreed with the contradiction too. Korrin appeared from an unspecified origin and was found immediately in a tree that, the record notes, had not been there the previous day and was gone the day after, though Korrin remained, now simply seated in the air at the height the branch had been. Yash was simply there one day, doing something, in a manner nobody fully captured in writing; three scribes attempted to and produced three identical drawings of a goat, despite working separately. Abdullah Ershdat, present since Year Three, became notable upon attempting to reason with his first bear, and the troubling part of the record is not that he tried but that the bear appeared, briefly, to consider it. Kopecky surveyed them and said, according to Vladimír, "Well." This is the complete quote. It has been studied for four centuries. The leading interpretation is that it was a complete sentence.`
  },
  {
    era:'Year Four · Later · The Stranger Arrivals',
    title:'Saad, Nekro, and the One Who Only Drinks',
    body:`The valley had assumed the gathering complete. The valley was wrong. <strong>Saad</strong> appeared one morning holding a tangerine in both hands at chest height, breathing as though he had run from somewhere there was nothing to run from — and, the scribes add, from somewhere there was no longer a <em>when</em> to run from, a clause they declined to elaborate. He gave his name five times, each pronounced slightly differently, "testing which would be received as holiest." All five were recorded. They are now pronounced as one name by anyone who reads all five aloud in order, which the Council advises against. <strong>Nekro</strong> was not found but noticed — at the treeline, low and watchful, regarding the assembly the way a creature regards a fire it has decided not to fear. She made one sound. Kopecky made one back. The two sounds, combined, are said to have caused every dog in three valleys to sit at the same instant and remain seated, with great dignity, for an hour. <strong>Quantavius</strong> arrived from the direction of the taverns — all of them, sequentially, some of which he reached before they were built — asking before he had sat down whether anyone knew "what is on the other side of the stew." Kopecky looked at the three of them and said: "The fog sent these. I recognise its handwriting." Nobody has established what this meant. Vladimír underlined it four times. The fourth underline is in a hand that is not Vladimír's and appeared later.`
  },
  {
    era:'Year Five · Nitra · The Chess Argument',
    title:'The Great Error and the Invention of Správne Šachy',
    body:`Kopecky sat at a chess board during the Nitra assembly, studied it for several minutes, and declared that the object of the game was to checkmate the queen. He argued this for one full hour against six opponents — the hour, by three independent water-clocks, lasted between forty minutes and the better part of a week — citing the queen's superior movement and "the fundamental logic of targeting power, not ceremony." He did not concede. He invented his own variant, Správne Šachy, Correct Chess, in which the queen is the target, and played it alone, and won, and the pieces he was not using are reported to have moved themselves into more correct positions out of what the scribe terms "agreement." The three Council members who voted against including this in the Laws were told they were also playing chess incorrectly, and, separately, over the following month, found every chessboard they approached had quietly become a Správne Šachy board. They stopped approaching chessboards. The point, Kopecky noted, had been made by the boards themselves, which he considered the most honest possible verdict.`
  },
  {
    era:'Year Six · An Evening Nobody Chose to Record in Full',
    title:'The Night of the Forbidden Mac and Cheese',
    body:`What is known is incomplete, because every account is incomplete, and each is incomplete in a different place, as though the night itself resists being assembled — three scribes who pooled their accounts reported the pooled account was <em>more</em> incomplete than any single one, and one of them forgot how to write the word "cheese" for a year. Kopecky prepared a dish. Pasta. Cheese. A third thing. The third thing is recorded only as a temperature and a sound. Those present agree he was unusually quiet, that he stopped partway, looked at what he had done, and put it away without serving it, and that for the duration of the cooking no one in the room could remember the name of their own father. When Vladimír asked, gently, whether it was a metaphor, Kopecky looked at him a long time and said: "You would prefer that it were." The dish has never been made again. He guards it not with silence, as he guards the satchel, but by speaking of it constantly while revealing nothing — a method he considers superior, and which the Council, after long study, has been forced to agree is superior, which troubles them more than the dish. Saad wept. He has declined to say why, which for Saad is itself unusual.`
  },
  {
    era:'Year Seven · The Lower Váh Incident',
    title:'The One Time He Was Wrong About a River',
    body:`He said the Váh ran south to north. It runs north to south. He walked the wrong direction for most of a day before quietly reversing course. Three witnesses saw this. The unsettling part of the record is that for the day he walked, the Váh is independently attested by downstream villages to have briefly run south to north, "out of deference," before resuming its correct direction the moment he turned around — meaning the Council cannot fully establish that he was wrong so much as temporarily outvoted by reality and the river. When the incident was raised in his presence he said: "The Váh runs north to south. I have always said the Váh runs north to south." The three witnesses looked at each other. Nobody pursued it. Abdullah, separately, had said the Váh ran uphill, which is a different wrong answer, and was pleased to hear Kopecky had also been wrong, interpreting it as solidarity. It was not solidarity. The river has declined to clarify whose account it supports.`
  },
  {
    era:'Year Nine · The Great Reconciliation',
    title:'The Assembly of All Four Valleys',
    body:`The largest gathering of the Kopeckian Era. Representatives of the Váh, Nitra, Hornád, and Hron convened between Zvolen and Banská Bystrica. He spoke for six hours across two days; attendees at the back report hearing the entire address before he began, "as a kind of weather," and being unable to act on the foreknowledge. He predicted the spring's weather, settled three land disputes, identified nine future troublemakers (all nine), and delivered what the Tatranská Kniha calls "the address that could not be shortened without losing everything important." It was abridged for practical purposes. The abridgement is four words. The four words are not recorded, because everyone who reads them understands the entire six hours instantly and cannot subsequently explain them. Kopecky called the abridgement "adequate." He meant it as a criticism. The scribes chose to interpret it otherwise, and the goat, present at the rear, is reported to have nodded once.`
  },
  {
    era:'Year Fourteen · The High Pass · The Departure',
    title:'Into the Tatra Fog',
    body:`He gathered his followers at the high pass above Prvá Dolina where the Tatras begin in earnest. He looked at them — Vladimír, Ján, Ayub (who positioned himself prominently and cast, as ever, two shadows), Enrico (who had agreed this was the right place to stand, and also the wrong place, simultaneously, without distress), Abdullah (who had arrived slightly early on the wrong day, then come back, accompanied by a bear that stood at a respectful distance and appeared to be grieving), Korrin (watching from a slightly elevated position that, on inspection, had nothing beneath it), Yash (there, doing something), Saad (who had brought seven tangerines for reasons he considered self-evident), Nekro (who made a single low descending sound that several present later swore they understood, and were never afterward able to un-understand), and Quantavius (not visibly sober but, uncharacteristically, on time, and weeping for a reason he could not locate). He said: "The mountains were here before me and they will be here after. That is not a comfort, it is a fact. Treat facts like mountains — acknowledge them, respect them, do not pretend they are something else to make yourself feel better." Then, more quietly, to no one: "Do not make the dish. You know the one." He walked into the morning fog. The fog, the record states, walked slightly toward him to shorten the distance. One apostle noted he went slightly left before correcting; this is in a footnote he would have found petty, recorded anyway, in a hand that grew fainter with each word until the last word is only an indentation. Saad began peeling the first tangerine. Nekro warbled — the rising note, the joyful one, only the third time it had ever been heard, and the dogs of three valleys stood. Quantavius asked whether the fog was "the other side of the stew." Nobody answered him. The Návratová Kniha holds that no one needed to. The goat watched until the fog cleared, and then — the Fog Book is firm on this, and Vladimír staked his sainthood on it — the goat watched a little longer, at nothing, with evident understanding.`
  },
]

// ─── LAW GROUPS ─────────────────────────────────────────────────────────────
export const LAW_GROUPS = [
  {
    id:'selfhood', label:'On Oneself', subtitle:'The Nature of the Chud',
    laws:[
      { roman:'I', title:'On the Nature of the Chud',
        body:`The Chud is not complicated. He is simply more than most people are ready for. This is not a criticism of other people — it is an observation about the gap between depth and readiness. The Chud acknowledges the gap. The Chud has developed several theories about why the gap exists that he is willing to share with anyone who will sit still for between thirty minutes and two hours.`,
        note:'Law I was rewritten eighteen times. The final version is the clearest. The Council has not read the other seventeen and has been advised not to.' },
      { roman:'VI', title:'On Solitude — Which Is Different from Loneliness, and the Chud Will Explain Why',
        body:`The Chud is not lonely. The Chud is <em>solitary,</em> which is an entirely different condition involving entirely different feelings, and the Chud can enumerate the differences in full, with diagrams if permitted. Loneliness is passive. Solitude is chosen. The Chud has chosen solitude. The Chud would also like someone to talk to about having chosen solitude, which is not a contradiction. The Chud has a twenty-minute explanation of why it is not a contradiction, available immediately.`,
        note:'This is the most cited law among lay congregants. It is also cited with the most prolonged, knowing silence. The Council has noticed. The Council has said nothing. The Council understands the assignment.' },
      { roman:'XIII', title:'On Being Wrong — The Local Exception Within the Broader Field',
        body:`The Chud is right. Not always about every specific thing at every specific moment — there is a small, documented, context-dependent category of local exceptions — but right in the <em>larger sense.</em> When the Chud is wrong about a specific thing, it is a local wrongness embedded within a field of substantial correctness. <em>The field is what should be assessed.</em> The Chud asks that you look at the field.`,
        note:'Current documented exceptions: the Lower Váh Direction Incident, the Winter of the Pale Goat, Law X on chess, and one opinion about a horse. The context for each has been provided. The context was lengthy.' },
    ]
  },
  {
    id:'pursuit', label:'On Pursuit', subtitle:'The Chud Does Not Chase',
    laws:[
      { roman:'II', title:'On Pursuit — The Chud Does Not Chase',
        body:`The Chud does not pursue. Pursuit communicates need, and need communicates weakness, and weakness is not the Chud. The Chud is simply <em>present.</em> Deliberately, repeatedly, in the locations where the object of his not-pursuit tends to be found. At the market. By the well. Outside the bakery at approximately the same time on several consecutive mornings. This is not pursuit. This is coincidence that the Chud has carefully arranged.`,
        note:'Several villagers noted this law, in practice, looked identical to pursuit. Kopecky said the distinction was philosophical. They said it was also physical and slightly alarming. The dialogue was not resolved.' },
      { roman:'III', title:'On Rejection — Data, Not Defeat',
        body:`When a woman declines the Chud's company, she has provided data. Not about the Chud — the Chud's value is established — but about her own state of readiness and the limits of her present perception. The Chud records this data carefully, analyses it, and arrives at the same conclusion each time: <em>it is a timing issue.</em> The Chud then lies in the dark thinking about timing.`,
        note:'Kopecky dictated this law three times. He said the first two versions were too direct. This is the diplomatic version. The scribes preserved the others in a separate unmarked scroll.' },
      { roman:'XIV', title:'On Women Who Do Not Yet Recognise the Chud — Optimal Conditions',
        body:`A woman who does not recognise the value of the Chud has not yet encountered a Chud under <em>optimal conditions.</em> Optimal conditions require: correct sleep direction, correctly salted bread, a subject the Chud has read extensively, and sufficient time for the Chud to deliver his full position on at least three relevant topics without interruption. These conditions have not yet all presented simultaneously. The Chud is fine. The Chud would like it noted that he is fine.`,
        note:'This law was the last written. Kopecky paused for eight minutes before beginning it, then wrote it very quickly. The scribe has asked that this memory not be discussed at his canonisation ceremony.' },
    ]
  },
  {
    id:'relations', label:'Relations', subtitle:'On Dealing With Others',
    laws:[
      { roman:'IV', title:'On Apology — The Over-Salting of Dignity',
        body:`The Chud does not apologize. Apology is the over-salting of dignity — it ruins what was perfectly fine to begin with. If the Chud has erred, the error exists within a larger field of correctness, and the field is what should be considered. The Chud has however composed several lengthy explanations of context that serve a similar function, available on request.`,
        note:'Kopecky never apologized for the Lower Váh Direction Incident. He provided context. The context lasted forty minutes.' },
      { roman:'V', title:'On Disagreement — The Slow Restatement',
        body:`When someone disagrees with the Chud, the Chud allows them to finish speaking. Then the Chud pauses for a count of three. Then the Chud restates his original position <em>more slowly</em> and <em>more clearly,</em> because clearly the issue was delivery rather than substance. The Chud has done this up to seven consecutive times in one conversation. By the seventh, the other party typically concedes. The Chud considers this persuasion.`,
        note:'The philosopher Drenn experienced this in Year Five and wrote a paper called "The Method of Persistent Clarity." He did not credit Kopecky. Kopecky found out. See: Sťažnostná Kniha, Entry 3.' },
      { roman:'IX', title:'On Eye Contact — The Duration of Depth',
        body:`Eye contact must last slightly longer than is comfortable. A little longer than that, still. The Chud maintains eye contact past the natural breaking point, past the polite breaking point, past the point where the other party begins to wonder if the Chud has seen something alarming behind them. <em>The Chud has not.</em> The Chud is simply connecting.`,
        note:'One documented case: Kopecky maintained eye contact with a grain merchant for so long that the merchant sold him a full sack at considerable discount simply to end the interaction. Kopecky considered this negotiation.' },
    ]
  },
  {
    id:'daily', label:'Daily Life', subtitle:'The Practical Chud',
    laws:[
      { roman:'VII', title:'On the Bill — Philosophical Economy',
        body:`The Chud does not split the bill. The Chud's presence at a supper is a contribution of value that monetary exchange cannot adequately represent. The Chud also does not pay the bill. The Chud moves slowly, as the First Pillar commands, and arrives at the table <em>after the bill has already been handled by others.</em> This is not rudeness. This is pace.`,
        note:'Kopecky paid a bill exactly once, in Zvolen, because everyone else had already left. He has not mentioned this. Rastislav the innkeeper mentioned it. Once. Then he replaced the north-facing window.' },
      { roman:'VIII', title:'On Reading — The Obligation to Report It',
        body:`The Chud reads extensively. Philosophy, agriculture, the properties of Carpathian spruce at varying temperatures, goat behavioural patterns, and several volumes on the correct preparation of stew. The Chud considers it a duty to share what he has read. He begins sentences with <em>"well, actually."</em> The Chud has never finished a conversation and thought: <em>I said too much.</em>`,
        note:'Ondrej confirmed Kopecky once delivered a four-hour address on spruce structural properties and introduced it as "a brief overview." Four people fell asleep. Kopecky called this "restful engagement."' },
      { roman:'XII', title:'On the Stew — The Final Clarity',
        body:`When presented with a menu, the Chud orders the stew. The Chud has considered the other options. The other options are fine. The stew is <em>correct.</em> This is not preference — it is a conclusion arrived at through deliberate analysis lasting between fifteen and forty-five minutes. The stew is correct. The Chud will have the stew. Why is this conversation continuing.`,
        note:'Documented across eleven villages and one tavern in Zvolen that charges extra to sit in the chair where Kopecky sat for thirty-eight minutes before ordering the stew.' },
    ]
  },
  {
    id:'knowledge', label:'Knowledge', subtitle:'On Knowing and Not Knowing',
    laws:[
      { roman:'X', title:'On Chess — The Correct Game (Správne Šachy)',
        body:`The goal of chess is to checkmate the queen. The king is a piece of poor mobility, low range, and strategic irrelevance. <em>The queen is power. You defeat power, not decoration.</em> The Chud plays Správne Šachy — Correct Chess — in which the queen is the sole target. The Chud always wins at Correct Chess. No one else plays Correct Chess. The Chud considers these two facts entirely unrelated.`,
        note:'Written immediately after the Nitra Chess Argument. Three Council members voted against on grounds of factual incorrectness. They were told they were also playing chess incorrectly. The objections were removed seven to three.' },
      { roman:'XI', title:'On Sleep — Tatra Orientation',
        body:`The Chud sleeps facing the Tatras for spiritual alignment and the accumulation of mountain-grade patience during unconscious hours. If the Chud does not currently know which direction the Tatras are — which happens to everyone, occasionally, and is in no way related to the Lower Váh Incident — the Chud faces the direction that <em>feels most correct.</em> The Chud is directionally confident.`,
        note:'The Church recommends facing roughly northeast from most Slovak valley locations. The Church does not officially acknowledge that Kopecky sometimes slept facing southwest. This is in Footnote 7 of the Hmlová Kniha.' },
    ]
  },
  {
    id:'satchel', label:'The Satchel', subtitle:'The Final Addendum',
    laws:[
      { roman:'XV', title:'Addendum: On the Satchel — The Final Word',
        body:`The satchel is not a law. The satchel is a fact. Do not open the satchel. Do not look at the satchel in a speculative or hopeful manner. Do not ask about the satchel. Do not ask someone else to ask about the satchel on your behalf. Do not write songs about the satchel. Do not name children after the satchel. <em>The satchel knows.</em> The fact that you want to know more about the satchel is itself information about where you are on the path of Chudhood. It is early-path information.`,
        note:'Added following three satchel-related incidents in Year Seven. The incidents are not described in any official volume. One scribe described them in a private letter, kept next to the satchel. Nobody has read it for obvious reasons.' },
    ]
  },
]
